/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhuyawen_android_ffmpegwrapper_TestJni */

#ifndef _Included_com_zhuyawen_android_ffmpegwrapper_TestJni
#define _Included_com_zhuyawen_android_ffmpegwrapper_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhuyawen_android_ffmpegwrapper_TestJni
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhuyawen_android_ffmpegwrapper_TestJni_init
  (JNIEnv *, jclass);

/*
 * Class:     com_zhuyawen_android_ffmpegwrapper_TestJni
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zhuyawen_android_ffmpegwrapper_TestJni_getInt
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
